version: '3.8'

services:
  api:
    build: .
    container_name: ledger-api
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src/:/usr/src/app/src/
    command: yarn start:prod

#   mongo:
#     image: mongo:6
#     container_name: ledger-db
#     restart: always
#     ports:
#       - '27017:27017'
#     volumes:
#       - .:/data/db

# # volumes:
# #   mongo_data: